amq:
  admin_queue_expiry: 3600000
  blocked_connection_timeout: 5
  connection_attempts: 3
  connections:
    admin:
      password: password
      port: 15672
      ssl:
        ca_cert: null
        ca_verify: true
        client_cert: null
        enabled: false
      user: beer_garden
    message:
      password: password
      port: 5672
      ssl:
        ca_cert: null
        ca_verify: true
        client_cert: null
        enabled: false
      user: beer_garden
  exchange: beer_garden
  heartbeat_interval: 3600
  host: localhost
  virtual_host: /
application:
  allow_unsafe_templates: false
  cors_enabled: true
  debug_mode: true
  icon_default: fa-beer
  name: Beer Garden
auth:
  enabled: false
  guest_login_enabled: true
  token:
    algorithm: HS256
    lifetime: 1200
    secret: IAMSUPERSECRET
db:
  connection:
    host: localhost
    password: null
    port: 27017
    username: null
  name: beer_garden_v3
  ttl:
    action: -1
    event: 15
    info: 15
  type: mongo
entry:
  http:
    enable: true
    host: 0.0.0.0
    port: 2337
    public_fqdn: localhost
    ssl:
      ca_cert: null
      ca_path: null
      client_cert_verify: NONE
      enabled: false
      private_key: null
      public_key: null
    url_prefix: /
  thrift:
    enable: false
event:
  amq:
    enable: false
    exchange: event
    virtual_host: /
  mongo:
    enable: true
  parent:
    http:
      enable: false
      host: 0.0.0.0
      port: 2337
      public_fqdn: localhost
      skip_events:
      - DB_CREATE
      ssl:
        ca_cert: null
        ca_path: null
        client_cert_verify: NONE
        enabled: false
        private_key: null
        public_key: null
      url_prefix: /
garden:
  name: default
log:
  config_file: example_configs/logging-config.yaml
  file: null
  level: INFO
metrics:
  prometheus:
    enabled: false
    host: 0.0.0.0
    port: 2339
    url: http://localhost:3000
plugin:
  local:
    auth:
      password: password
      username: admin
    directory: ./plugins
    log_directory: null
    timeout:
      shutdown: 10
      startup: 2
  logging:
    config_file: example_configs/plugin-logging.yaml
    level: INFO
  status_heartbeat: 5
  status_timeout: 30
publish_hostname: localhost
scheduler:
  auth:
    password: null
    username: null
  job_defaults:
    coalesce: true
    max_instances: 3
  max_workers: 10
validator:
  command:
    timeout: 10
  url:
    ca_cert: null
    ca_verify: true
